- name: Testing playbook
  hosts: localhost
  connection: local
  vars:
    db_val: some_db
    db:
      some_dbsome_user:
        name: foo
    _db_username: "{{ workload[app].user[user].username }}"
    # _db_username: "{{ '{{ db.' + db_val + user + '.name }}' }}"
  tasks:
    - set_fact:
        db_username: "{{ _db_username }}"
    - debug:
        var: db_username
    - debug:
        msg: "{{db_username}}"